leftnav:
- identifier: 7a7dc326-dd34-4167-919d-167d7c05999a
  name: page 1
  url: /pages/sadfasd
  weight: 10
- identifier: 7df6fe73-1001-4851-8adb-a8b2aab727ac
  name: Video
  url: /resources/tiny-video
  weight: 20
